### ISSUE TITLE
Gutenberg editor breaks with custom post stati

### ISSUE THREAD

**Issue by tcrsavage** [humanmade/post-cloner#16] opened 2019-03-11 15:46 UTC
When a custom post status is registered, Gutenberg edit screens fatal error due to bad render handling.

<img width="940" alt="Screen Shot 2019-03-11 at 15 43 23" src="https://user-images.githubusercontent.com/907521/54136925-93ba3700-4414-11e9-91ec-aabe51e5f119.png">

```
Invariant Violation: DisplayPostCloningStatus(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
    at invariant (http://motogp.servus.local/wp-includes/js/dist/vendor/react-dom.js?ver=16.6.3:49:15)
    at reconcileChildFibers (http://motogp.servus.local/wp-includes/js/dist/vendor/react-dom.js?ver=16.6.3:13883:13)
    at reconcileChildren (http://motogp.servus.local/wp-includes/js/dist/vendor/react-dom.js?ver=16.6.3:14202:28)
    at mountIndeterminateComponent (http://motogp.servus.local/wp-includes/js/dist/vendor/react-dom.js?ver=16.6.3:14764:5)
    at beginWork (http://motogp.servus.local/wp-includes/js/dist/vendor/react-dom.js?ver=16.6.3:15187:16)
    at performUnitOfWork (http://motogp.servus.local/wp-includes/js/dist/vendor/react-dom.js?ver=16.6.3:17944:12)
    at workLoop (http://motogp.servus.local/wp-includes/js/dist/vendor/react-dom.js?ver=16.6.3:17984:24)
    at renderRoot (http://motogp.servus.local/wp-includes/js/dist/vendor/react-dom.js?ver=16.6.3:18070:7)
    at performWorkOnRoot (http://motogp.servus.local/wp-includes/js/dist/vendor/react-dom.js?ver=16.6.3:18961:7)
    at performWork (http://motogp.servus.local/wp-includes/js/dist/vendor/react-dom.js?ver=16.6.3:18873:7)
```

**To reproduce**

Register a custom post status, assign the status to a post, edit the post with gutenberg

```
	register_post_status( 'imported', [
		'label'                     => _x( 'Imported', 'post status' ),
		'public'                    => false,
		'exclude_from_search'       => true,
		'show_in_admin_all_list'    => true,
		'show_in_admin_status_list' => true,
		'label_count'               => _n_noop( 'Imported <span class="count">(%s)</span>', 'Imported <span class="count">(%s)</span>' ),
	] );
```

**Comment by tcrsavage** [comment] 2019-03-11 15:48
Can be bypassed by adding the custom status to the clonable stati

```
add_filter( 'post_cloner_clonable_statuses', function( $stati ) {
    $stati[] = 'imported'; 
    return $stati 
} );
```

**Comment by pdewouters** [comment] 2020-07-30 10:44
I can't reproduce this. I have registered the custom status, and set a post to this status with WP CLI. But I don't get an error in Gutenberg.
<img width="770" alt="Screenshot 2020-07-30 at 11 44 20" src="https://user-images.githubusercontent.com/30460/88914142-13d77b80-d25a-11ea-8ff2-fb7e2a546a71.png">

**Comment by roborourke** [comment] 2020-07-30 12:07
@pdewouters cheers for checking, looks like this must have been fixed in a subsequent version of gutenberg

**Closed by roborourke** 2020-07-30 12:07 UTC
Labels: bug
